logging:
  level:
    com.pushkin: ${LOG_LEVEL:info}

jwt:
  ttl_seconds: ${JWT_TTL_SECONDS:31536000}
  signing-key: ${JWT_KEY:test_key}

users:
  swagger-admin:
    login: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:*}

spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://test:test@localhost:27017/weather}
  profiles:
    active: "prod"

openweathermap:
  api-key: ${OPENWEATHERMAP_API_KEY:}
  url: ${OPENWEATHERMAP_BASE_URL:https://api.openweathermap.org}
  limit: ${OPENWEATHERMAP_LIMIT:10}

weather:
  cache:
    ttl_seconds: ${WEATHER_CACHE_TTL_SECONDS:3600}

geodata:
  cache:
    ttl_seconds: ${GEODATA_CACHE_TTL_SECONDS:43200}

server:
  error:
    include-message: always
  forward-headers-strategy: framework
