name: Build and deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Install SSH key
        run: mkdir ~/.ssh && chmod 700 ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: Deploy to PROD Server
        if: github.ref == 'refs/heads/master'
        run: |
          ls -la && find build -ls
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "sudo rm -rf ${{ vars.SSH_PATH_MASTER }}/* && mkdir -p ${{ vars.SSH_PATH_MASTER }}/libs"
          scp -r -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no build/libs/weather_app_backend-*-SNAPSHOT.jar ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}:${{ vars.SSH_PATH_MASTER }}/libs
          scp -r -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no docker/Dockerfile ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}:${{ vars.SSH_PATH_MASTER }}
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "cd weather && ./start.sh"
